M48
; DRILL file {KiCad 9.0.6} date 2025-12-01T20:05:59-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-01T20:05:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X73.01Y-97.0
X93.5Y-97.0
T2
X23.0Y-62.5
X23.0Y-111.5
X100.0Y-111.5
X100.5Y-62.5
M30
